version: '3.8'
services:

  server:
    environment:
      - DOCKER_ENV=1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - ./certs:/app/certs 

  socket:
    environment:
      - DOCKER_ENV=1
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./socket:/app
      - ./certs:/app/certs 
